<a href="https://colab.research.google.com/github/AlimamHu/machine_learnin_tree/blob/main/Regression_with_deep_mind_understaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 1 
* all Regression Allgorithm use 
* Quick look theory part
* all Regression Allgorithm use again mind but you know how it work & why.
* all Important point cover What, why & how . (pros & coes)
## Deep Dive into the Regression  it make you Advance level player in the game.
* make Algorithms from skreatch.
* & do a few projects for real world exprences. 

Notics :- You must perelley learn the some statistics & Probabilty use below link

statistics:-    https://youtube.com/playlist?list=PL1328115D3D8A2566

probability:-   https://www.youtube.com/playlist?list=PLC58778F28211FA19

After Finishing above topic you changing you level expert to max expert in Regression 

# All Regression Allgorithm use for how to use it.
(because it make question on your brain to help in study. this is also work)

**so, what is Regression? rise in you mind.**

Regression analysis is a form of predictive modelling technique which investigates the relationship between a dependent (target) and independent variable (s) (predictor). 

This technique is used for forecasting, time series modelling and finding the causal effect relationship between the variables.

## Types of Regression 
* Linear Regression
* Logistic Regression
* Polynomial Regression
* Stepwise Regression
* Ridge Regression
* Lasso Regression
* ElasticNet Regression


# Linear Regression     

In [1]:
print('hello')

hello


In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [3]:
X=np.array([[1,1],[1,2],[2,2],[2,3]])
y=np.dot(X,np.array([1,2])) +3        # 1*x_0 + 2*x_1 +3 

In [4]:
X

array([[1, 1],
       [1, 2],
       [2, 2],
       [2, 3]])

In [5]:
y

array([ 6,  8,  9, 11])

In [6]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
model.predict([[6,7]])

array([23.])

In [8]:
model.predict([[7,7]])

array([24.])

In [9]:
model.coef_

array([1., 2.])

In [10]:
model.intercept_

3.0000000000000018

In [11]:
model.score(X,y)

1.0

In [12]:
model.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'normalize': False}

# Polynomial Regression

In [13]:
model.intercept_+(model.coef_*X**2)

array([[ 4.,  5.],
       [ 4., 11.],
       [ 7., 11.],
       [ 7., 21.]])

In [14]:
from sklearn.preprocessing import PolynomialFeatures

In [15]:
poly=PolynomialFeatures(degree=1)

In [16]:
poly.fit(X)

PolynomialFeatures(degree=1, include_bias=True, interaction_only=False,
                   order='C')

In [17]:
poly.fit_transform(X)

array([[1., 1., 1.],
       [1., 1., 2.],
       [1., 2., 2.],
       [1., 2., 3.]])

In [18]:
X

array([[1, 1],
       [1, 2],
       [2, 2],
       [2, 3]])

# Logistic Regression

In [19]:
from sklearn.datasets import load_iris

In [20]:
X,y=load_iris(return_X_y=True)

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
model1=LogisticRegression()

In [23]:
X.size

600

In [24]:
model1.fit(X[0:100,np.newaxis],y[0:100])

ValueError: ignored

In [ ]:
X.shape

# Stepwise Regression

In [26]:
import numpy as np
import statsmodels.api as sm
def get_stats():
    x = X
    results = sm.OLS(y, x).fit()
    print(results.summary())
    
get_stats()

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.972
Model:                            OLS   Adj. R-squared (uncentered):              0.971
Method:                 Least Squares   F-statistic:                              1267.
Date:                Tue, 18 May 2021   Prob (F-statistic):                   3.17e-112
Time:                        15:07:19   Log-Likelihood:                          17.009
No. Observations:                 150   AIC:                                     -26.02
Df Residuals:                     146   BIC:                                     -13.98
Df Model:                           4                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

# Ridge Regression

In [27]:
from sklearn.linear_model import Ridge
model3=Ridge()

In [28]:
n_samples, n_features = 10, 5

rng = np.random.RandomState(0)

y = rng.randn(n_samples)


X = rng.randn(n_samples, n_features)

clf = Ridge(alpha=1.0)


clf.fit(X, y)




Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [29]:
clf.predict(X)

array([ 0.95424223,  0.48712089,  1.10388121,  1.79105759,  1.05769745,
       -0.07915715,  1.12314109, -0.22941441,  0.64906337,  0.52259943])

In [30]:
y

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

# ElasticNet Regression

In [31]:
print('helo')

helo


In [32]:
from sklearn.linear_model import ElasticNet
from sklearn.datasets import make_regression

In [40]:
X,y=make_regression(n_features=2,random_state=42)

In [42]:
X.shape

(100, 2)

In [43]:
y.shape

(100,)

In [44]:
regr=ElasticNet(random_state=41)

In [45]:
regr.fit(X,y)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=41, selection='cyclic', tol=0.0001, warm_start=False)